### spaCy

Results not too great with TfidfVectorizer alone or in tandem with Gensim simple_preprocess.
Ideas for improving are more specialized NLP and/or gathering better book synopsis data.

But first... gonna see how spaCy does for me

In [43]:
import numpy as np
import pandas as pd
import re
import spacy
from spacy.tokenizer import Tokenizer
import enchant
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

In [12]:
df = pd.read_csv('master_books.csv')
print(df.shape)
df.head()

(19707, 6)


title           author  \
0            The Hunger Games (The Hunger Games, #1)  Suzanne Collins   
1  Harry Potter and the Order of the Phoenix (Har...     J.K. Rowling   
2                              To Kill a Mockingbird       Harper Lee   
3                                Pride and Prejudice      Jane Austen   
4                            Twilight (Twilight, #1)  Stephenie Meyer   

                                rating  \
0  4.33 avg rating — 6,191,931 ratings   
1  4.50 avg rating — 2,414,060 ratings   
2  4.28 avg rating — 4,348,656 ratings   
3  4.26 avg rating — 2,886,703 ratings   
4  3.59 avg rating — 4,815,701 ratings   

                                         description language  \
0  WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...  English   
1  There is a door at the end of a silent corrido...  English   
2  The unforgettable novel of a childhood in a sl...  English   
3  Alternate cover edition of ISBN 9780679783268S...  English   
4  About three things I was absolutely positive.\...  English   

                                 isbn  
0  0439023483 (ISBN13: 9780439023481)  
1  0439358078 (ISBN13: 9780439358071)  
2                                 NaN  
3                                 NaN  
4  0316015849 (ISBN13: 9780316015844)

In [13]:
df.isnull().sum()

title             0
author            0
rating            0
description     676
language       1617
isbn           4596
dtype: int64

In [15]:
mask = df.description.isnull()

df[~mask].shape

(19031, 6)

In [16]:
df = df.dropna(subset=['description'])
df.shape

(19031, 6)

In [17]:
df['text'] = [re.sub('\W+', ' ', text.lower()) for text in df['description']]

C:\Users\jayja\anaconda3\envs\books-kernel\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [18]:
# ~16000 books with 'English' as the language - save those
df['language'].value_counts()

English                                15812
Arabic                                   408
Spanish                                  261
French                                   207
German                                   156
Indonesian                               154
Portuguese                               110
Italian                                   86
Dutch                                     86
Turkish                                   73
Persian                                   46
Polish                                    40
Czech                                     33
Romanian                                  29
Bulgarian                                 28
Malay                                     25
Swedish                                   24
Japanese                                  22
Greek, Modern (1453-)                     20
Russian                                   16
Urdu                                      16
Estonian                                  12
Vietnamese

In [19]:
df = df[df['language'] == 'English']
df.shape

(15812, 7)

In [6]:
english = enchant.Dict("en_US")

def check_english(book, english=english):
    ten_words = book.split()[:10]
    
    word_is_english = []
    
    for word in ten_words:
        word_is_english.append(english.check(word))
    
    english_words = word_is_english.count(True)
    return english_words / len(word_is_english)

In [20]:
df['is_english'] = df['text'].apply(check_english)

df.head(10)

title  \
0            The Hunger Games (The Hunger Games, #1)   
1  Harry Potter and the Order of the Phoenix (Har...   
2                              To Kill a Mockingbird   
3                                Pride and Prejudice   
4                            Twilight (Twilight, #1)   
5                                     The Book Thief   
6  The Chronicles of Narnia (Chronicles of Narnia...   
7                                        Animal Farm   
8  J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...   
9                                 Gone with the Wind   

                            author                               rating  \
0                  Suzanne Collins  4.33 avg rating — 6,191,931 ratings   
1                     J.K. Rowling  4.50 avg rating — 2,414,060 ratings   
2                       Harper Lee  4.28 avg rating — 4,348,656 ratings   
3                      Jane Austen  4.26 avg rating — 2,886,703 ratings   
4                  Stephenie Meyer  3.59 avg rating — 4,815,701 ratings   
5  Markus Zusak (Goodreads Author)  4.37 avg rating — 1,767,200 ratings   
6                       C.S. Lewis    4.26 avg rating — 498,771 ratings   
7                    George Orwell  3.94 avg rating — 2,631,549 ratings   
8                   J.R.R. Tolkien    4.60 avg rating — 107,831 ratings   
9                Margaret Mitchell  4.30 avg rating — 1,054,418 ratings   

                                         description language  \
0  WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...  English   
1  There is a door at the end of a silent corrido...  English   
2  The unforgettable novel of a childhood in a sl...  English   
3  Alternate cover edition of ISBN 9780679783268S...  English   
4  About three things I was absolutely positive.\...  English   
5  It is 1939. Nazi Germany. The country is holdi...  English   
6  Journeys to the end of the world, fantastic cr...  English   
7  Librarian's note: There is an Alternate Cover ...  English   
8  This four-volume, boxed set contains J.R.R. To...  English   
9  Scarlett O'Hara, the beautiful, spoiled daught...  English   

                                 isbn  \
0  0439023483 (ISBN13: 9780439023481)   
1  0439358078 (ISBN13: 9780439358071)   
2                                 NaN   
3                                 NaN   
4  0316015849 (ISBN13: 9780316015844)   
5  0375831002 (ISBN13: 9780375831003)   
6                                 NaN   
7  0451526341 (ISBN13: 9780451526342)   
8  0345538374 (ISBN13: 9780345538376)   
9  0446675539 (ISBN13: 9780446675536)   

                                                text  is_english  
0  winning means fame and fortune losing means ce...         1.0  
1  there is a door at the end of a silent corrido...         1.0  
2  the unforgettable novel of a childhood in a sl...         1.0  
3  alternate cover edition of isbn 9780679783268s...         0.8  
4  about three things i was absolutely positive f...         0.9  
5  it is 1939 nazi germany the country is holding...         0.8  
6  journeys to the end of the world fantastic cre...         1.0  
7  librarian s note there is an alternate cover e...         1.0  
8  this four volume boxed set contains j r r tolk...         0.9  
9  scarlett o hara the beautiful spoiled daughter...         0.8

In [21]:
mask = df['is_english'] >= .5

df = df[mask]

In [22]:
df.shape

(15742, 8)

In [23]:
def get_description_length(book):
    return len(book.split())

df['descrip_len'] = df['text'].apply(get_description_length)

In [24]:
len(df.query("descrip_len <= 6"))

33

In [26]:
# dropping books with descriptions shorter than 7 words
mask = df['descrip_len'] > 6

df = df[mask]

In [27]:
df.shape

(15709, 9)

In [28]:
seen = set()
def find_doubles(title, author, seen=seen):
    title_author = (title, author)
    if title_author not in seen:
        seen.add(title_author)
        return False
    else:
        return True

In [29]:
df['double'] = df.apply(lambda x: find_doubles(x.title, x.author), axis=1)

In [30]:
df['double'].value_counts()

False    12240
True      3469
Name: double, dtype: int64

In [31]:
mask = ~df['double']
df = df[mask]

In [32]:
df.shape

(12240, 10)

### First Model

In [33]:
nlp = spacy.load('en_core_web_sm')

In [36]:
tokenizer = Tokenizer(nlp.vocab)

In [39]:
def make_tokens(text, tokenizer=tokenizer):
    return [token.text for token in tokenizer(text) if token.is_stop == False] 

In [41]:
vect = TfidfVectorizer(tokenizer=make_tokens)

data = [''.join(s) for s in df['text']]

vect.fit(data)

C:\Users\jayja\anaconda3\envs\books-kernel\lib\site-packages\sklearn\feature_extraction\text.py:484: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"


TfidfVectorizer(tokenizer=<function make_tokens at 0x0000027F143C29D8>)

In [42]:
sparse = vect.transform(data)

dtm = pd.DataFrame(sparse.todense(), columns=vect.get_feature_names())

dtm.head()

0   00  000  001  007   01  0140422536  0141183829   02  ...  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0         0.0         0.0  0.0  ...   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0         0.0         0.0  0.0  ...   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0         0.0         0.0  0.0  ...   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0         0.0         0.0  0.0  ...   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0         0.0         0.0  0.0  ...   

   человечества  чтобы  美しさと哀しみと  fierce  find  fired  first  flame  flavorful  \
0           0.0    0.0       0.0    0.0  0.0   0.0   0.0   0.0       0.0   
1           0.0    0.0       0.0    0.0  0.0   0.0   0.0   0.0       0.0   
2           0.0    0.0       0.0    0.0  0.0   0.0   0.0   0.0       0.0   
3           0.0    0.0       0.0    0.0  0.0   0.0   0.0   0.0       0.0   
4           0.0    0.0       0.0    0.0  0.0   0.0   0.0   0.0       0.0   

   flavors  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0  

[5 rows x 56912 columns]

In [47]:
nn = NearestNeighbors(n_neighbors=5, algorithm='auto')

nn.fit(dtm)

NearestNeighbors()

In [48]:
new = ['A magical boy fights evil with his friends at school']
new_vected = vect.transform(new)
new_df = pd.DataFrame(new_vected.todense(), columns=vect.get_feature_names())
nn.kneighbors(new_df)

(array([[1.2097142 , 1.2504767 , 1.27759368, 1.28108184, 1.28417914]]),
 array([[ 2571,  5828,  4857,  8394, 11013]], dtype=int64))

In [53]:
df.iloc[11013]

title                                Finding Sky (Benedicts, #1)
author                          Joss Stirling (Goodreads Author)
rating                          4.09 avg rating — 16,941 ratings
description    You have half our gifts, I have the other . . ...
language                                                 English
isbn                          0192732137 (ISBN13: 9780192732132)
text           you have half our gifts i have the other when ...
is_english                                                     1
descrip_len                                                   79
double                                                     False
tokens         [half, gifts, english, girl, sky, catches, gli...
Name: 13850, dtype: object

In [54]:
new = ['Becoming a better person']
new_vected = vect.transform(new)
new_df = pd.DataFrame(new_vected.todense(), columns=vect.get_feature_names())
nn.kneighbors(new_df)

(array([[1.2175296 , 1.26338627, 1.27600551, 1.27747555, 1.28410213]]),
 array([[ 5988,  5529,  8350,  8325, 11530]], dtype=int64))

In [58]:
df.iloc[8325]

title                                         After Twenty Years
author                                                  O. Henry
rating                             4.03 avg rating — 591 ratings
description    The skill of the legendary master of the twist...
language                                                 English
isbn                                                         NaN
text           the skill of the legendary master of the twist...
is_english                                                     1
descrip_len                                                   24
double                                                     False
tokens         [skill, legendary, master, twist, ending, shor...
Name: 9919, dtype: object